### PR TITLE
Fixes mouseup and ensure unbinding of keystroke events

### PR DESCRIPTION
**Pull request by tvdeyen**
Converted all mousdown events to mouseup events.
Ensuring that the keystroke event observers are getting unbinded if closing the selectbox (especially while cloking outside of the selectbox)

### CODE REVIEW

**Comment by tvdeyen** [comment]
Hmm, any luck with merging these pull request via github? I just saw that the old pullrequest is still open?

**Comment by MaxPower15** [comment]
Yeah, I should probably just close the old one. I manually merged in the changes for that a while ago.

**Comment by tvdeyen** [comment]
I made some more fixes. Just close this and I send a new one for these fixes.
That should work, I hope.

**Comment by MaxPower15** [comment]
Also, I'm not certain the mousedown events should be moved to mouseup events? I know this is generally how it is for buttons and the like, but my tests on the original `<select>` element opened on mousedown. Practically speaking, I do think it feels a little more responsive on mousedown. But I don't know if I like it.

Need to think for a day or two on this...

**Comment by tvdeyen** [comment]
Hmm, you are on windows? I am on a Mac and my selects all opening on mouseup, like all other buttons and gui elements in the whole operation system. This is very handy. Think of accidentally pressed buttons. With mouseup events you could move the mouse outside the element while holding down the button and after releasing the event does not fire on this element any more! Very nice ;)

**Comment by tvdeyen** [comment]
Could you please reopen the ticket? I accidentally hit comment and close ;)

**Comment by revsystems** [comment]
Yeah, I'm doing my tests on windows. I think you're right about this; I should definitely be taking UX cues from macs instead of windows.

I will try merging this soon, but it may be a few days. Busy with a few other projects at the moment. Really appreciate your contributions. Thanks

**Comment by tvdeyen** [comment]
You are always welcome. Glad to be a help with your wonderful plugin.

**Pull request merged**
